### ISSUE TITLE
Availablity Zone / ReplicationController / PersistentVolumes

### ISSUE THREAD

**Issue by nevetS** [xuwang/kube-aws-terraform#12]
Just a note.  I haven't fully vetted this out.

I have my AWS_REGION set to us-west-2.

One node was created in us-west-2a, the other in us-west-2b.

I created a persistent volume, and that volume was not binding to the node because the volume was created in us-west2b, but the node could not find the volume.  

After a bit of research, I discovered that ebs volumes are tied to not just the region, but the availability zone as well.  This means that if you bring down a pod tied to a persistent volume and bring it back up again in a node that is not in the same availability zone, it might not come back up because it cannot access the volume.

Of course, I had a whole different problem as well, which is that my volume was not created in the same namespace, which clouded my troubleshooting.

Still - it's worth digging into this a bit more and documenting either a recommendation or a warning about availability zones and persistent volumes.  Maybe I should have been more specific in my AWS_REGION setting, which would have led to a slightly less complex deployment.  It makes me wonder about how to test fail-over of services between zones.

**Comment by xueshanf** [comment]
@nevetS Because GCP/AWS cloud provider volumes do not cross zones,  the pod can only be created in the same zone as the volume through persistent volume claim. Not sure why your pod cannot find its volume. We should take a look at your pod, pv, pvc manifests. 

For high availability, if  your application has to use local attached disk, I think the best strategy is to provision more than one nodes on the zone that you have the PV defined. For cross zone fail-over, some kind of backup/restore process has to be in place at the application level, or use an centralized file system, such as EFS on AWS.

**Comment by xueshanf** [comment]
@nevetS do you need any follow up on this?

**Comment by nevetS** [comment]
I think I'm good at this point.  Thank you!
