### ISSUE TITLE
Vault "roles": required field is not set

### ISSUE THREAD

**Issue by stiks** [xuwang/kube-aws-terraform#21]
Vault configuration issue:

```
2 error(s) occurred:

* module.vault.aws_iam_instance_profile.instance_pool: "roles": required field is not set
* module.vault.aws_iam_instance_profile.instance_pool: : invalid or unknown key: role
make[1]: *** [apply] Error 1
make: *** [vault] Error 2
```

**Comment by xueshanf** [comment]
@stiks Terraform deprecated  roles in favour of role in iam_instance_profile, I think since 0.9.3. Since your cluster is not totally up yet, would you mind re-clone to a fresh location, and start it again with the latest changes? The default TF_VERSION is the latest. I updated envs.sh.sample to reflect this. Thanks for catching up the TF_VERSION error!

**Comment by stiks** [comment]
No issues anymore ;-) Cluster has been created ;-)
